--- # EC2 - Start/Stop/Terminate Module
- hosts: localhost
  connection: local
  remote_user: kdamera1
  become: yes
  gather_facts: yes
  tasks:
  - name: Manage the state of an instance
    ec2:
      instance_ids: xxxxxx #Your Instance Id's
      state: xxxxxx # The state of Ec2 instance you Require.

