--- #EC2 SNAPSHOT MODULE
- hosts: localhost
  connection: local
  remote_user: kdamera1
  gather_facts: no
  tasks:
  - name: Take a snapshot of the running instance root volume
    ec2_snapshot:
      instance_id: xxxxxx # your instance id
      device_name: /dev/xvda
      description: This is The Root Volume Snapshot
      wait: no
    register: snapshot

