--- # EC2 Volume Module
- hosts: localhost
  connection: local
  become: yes
  remote_user: kdamera1
  gather_facts: yes
  tasks:
  - name: Create a new volume and attach to running instance
    ec2_vol:
      instance: xxxxxxx #Your Instance-Id
      state: list
    register: volume_result
  - debug: msg= {{ volume_result }}
